#include "Presets.h"

#include "Engine/ChipDescriptors.h"

#include <algorithm>
#include <cctype>

namespace chipper
{
namespace
{

std::string presetKey(std::string_view text)
{
    std::string key(text.begin(), text.end());
    std::transform(key.begin(), key.end(), key.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    key.erase(std::remove_if(key.begin(), key.end(), [](char c) { return c == '_' || c == '-' || c == '/' || c == ' '; }), key.end());
    return key;
}

} // namespace

const std::vector<PresetInfo>& presetCatalog()
{
    static const std::vector<PresetInfo> presets {
        {
            "nes-hero-pulse",
            "NES Leads",
            "NES Hero Pulse",
            "Forward pulse lead with pulse stack and triangle support.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.67f, 0.38f, 0.12f, 0.78f },
            { true, true, true, false },
            0.0f,
            0,
            0,
            0,
            -9.0f,
            1789773.0
        },
        {
            "nes-triangle-bass",
            "NES Bass",
            "NES Triangle Bass",
            "Triangle-weighted bass with restrained pulse support.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::bass,
            PlayMode::stack,
            { 0.50f, 0.16f, 0.05f, 0.12f },
            { true, false, true, false },
            0.0f,
            0,
            0,
            0,
            -8.0f,
            1789773.0
        },
        {
            "nes-noise-snare",
            "NES Drums",
            "NES Noise Snare",
            "Short RP2A03 noise burst with triangle transient.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.33f, 0.12f, 0.86f, 0.42f },
            { false, false, true, true },
            0.78f,
            0,
            0,
            0,
            -10.0f,
            1789773.0
        },
        {
            "nes-coin-blip",
            "Arcade UI",
            "NES Coin Blip",
            "Bright short pulse pop for UI and pickup sounds.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::coin,
            PlayMode::stack,
            { 0.16f, 0.90f, 0.06f, 0.82f },
            { true, true, false, false },
            0.45f,
            0,
            0,
            0,
            -11.0f,
            1789773.0
        },
        {
            "nes-boss-damage",
            "Classic Game SFX",
            "NES Boss Damage",
            "Noisy RP2A03 impact with triangle thump and one pulse edge.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::hit,
            PlayMode::stack,
            { 0.45f, 0.25f, 0.76f, 0.64f },
            { true, false, true, true },
            0.60f,
            0,
            0,
            2,
            -12.0f,
            1789773.0
        },
        {
            "nes-power-up-rise",
            "Classic Game SFX",
            "NES Power-Up Rise",
            "Optimistic RP2A03 pulse stack with triangle lift.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::powerUp,
            PlayMode::stack,
            { 0.70f, 0.90f, 0.20f, 0.90f },
            { true, true, true, false },
            0.0f,
            0,
            0,
            0,
            -10.0f,
            1789773.0
        },
        {
            "dmg-wave-bass",
            "DMG Wave",
            "DMG Wave Bass",
            "Wave-channel bass body using a written triangle table.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::bass,
            PlayMode::stack,
            { 0.50f, 0.18f, 0.08f, 0.92f },
            { false, false, true, false },
            0.0f,
            1,
            0,
            0,
            -8.0f,
            4194304.0,
            0.0f,
            1
        },
        {
            "dmg-pocket-arp",
            "DMG Pulse",
            "DMG Pocket Arp",
            "Pulse and wave stack arranged for fast handheld arps.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.66f, 0.78f, 0.18f, 0.72f },
            { true, true, true, false },
            0.0f,
            4,
            0,
            0,
            -10.0f,
            4194304.0,
            0.0f,
            4
        },
        {
            "dmg-noise-hat",
            "DMG Drums",
            "DMG Noise Hat",
            "Narrow polynomial-noise percussion with short hardware decay.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.20f, 0.12f, 0.96f, 0.74f },
            { false, false, false, true },
            0.88f,
            0,
            0,
            0,
            -12.0f,
            4194304.0,
            0.0f,
            1
        },
        {
            "dmg-power-up-rise",
            "Classic Game SFX",
            "DMG Power-Up Rise",
            "Handheld pulse and wave stack for rising pickup gestures.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::powerUp,
            PlayMode::stack,
            { 0.70f, 0.90f, 0.18f, 0.86f },
            { true, true, true, false },
            0.0f,
            2,
            0,
            0,
            -10.0f,
            4194304.0,
            0.0f,
            4
        },
        {
            "sid-dirty-bass",
            "SID Bass",
            "SID Dirty Bass",
            "Dual pulse-voice C64 bass using SID pulse-width and sustain registers.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::bass,
            PlayMode::stack,
            { 0.48f, 0.18f, 0.40f, 0.82f },
            { true, true, false, false },
            0.28f,
            3,
            1,
            1,
            -9.0f,
            985248.0,
            0.58f,
            1,
            3,
            0,
            5
        },
        {
            "sid-pwm-lead",
            "SID PWM Leads",
            "SID PWM Lead",
            "Three SID voices stacked around pulse waveform control and voice detune.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.58f, 0.40f, 0.72f, 0.70f },
            { true, true, true, false },
            0.32f,
            3,
            1,
            1,
            -10.0f,
            985248.0,
            0.36f,
            2,
            3,
            3,
            1
        },
        {
            "sid-robot-arp",
            "SID FX",
            "SID Robot Arp",
            "Mixed saw, pulse, and triangle SID stack for robotic arps and tight pattern movement.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.50f, 0.78f, 0.85f, 0.60f },
            { true, true, true, false },
            0.25f,
            2,
            2,
            1,
            -10.0f,
            985248.0,
            0.42f,
            2,
            3,
            1,
            1
        },
        {
            "sid-noise-drum",
            "SID FX",
            "SID Noise Drum",
            "Noise waveform on SID voice 3 with a fast ADSR-style decay.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.50f, 0.10f, 0.80f, 0.20f },
            { false, false, true, false },
            0.95f,
            4,
            1,
            1,
            -12.0f,
            985248.0,
            0.18f,
            1,
            0,
            4,
            4
        },
        {
            "ym-three-voice-arp",
            "YM Arps",
            "YM Three-Voice Arp",
            "A/B/C fake-chord spread for demo-scene arpeggios.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.70f, 0.70f, 0.12f, 0.52f },
            { true, true, true, false },
            0.0f,
            0,
            0,
            0,
            -10.0f,
            2000000.0
        },
        {
            "ym-fake-chord-stack",
            "YM Arps",
            "YM Fake Chord Stack",
            "Three YM/AY tone channels voiced as a bright fake chord.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::stack,
            { 0.95f, 0.76f, 0.12f, 0.50f },
            { true, true, true, false },
            0.0f,
            0,
            0,
            0,
            -10.0f,
            2000000.0
        },
        {
            "ym-menu-beep",
            "YM Beeps",
            "YM Menu Beep",
            "Single-channel square beep with bright pitch gesture.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::coin,
            PlayMode::stack,
            { 0.15f, 0.82f, 0.08f, 0.50f },
            { true, false, false, false },
            0.0f,
            0,
            0,
            0,
            -9.0f,
            2000000.0
        },
        {
            "ym-noise-hat",
            "YM Noise Percussion",
            "YM Noise Hat",
            "Shared-noise percussion through channel A.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.25f, 0.10f, 0.92f, 0.18f },
            { true, false, false, true },
            0.0f,
            0,
            1,
            0,
            -12.0f,
            2000000.0
        },
        {
            "sn-psg-lead",
            "SN76489 / Sega PSG",
            "Sega PSG Lead",
            "Forward tone-channel lead across the SN76489 tone lanes.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.52f, 0.45f, 0.12f, 0.22f },
            { true, true, true, false },
            0.0f,
            0,
            0,
            0,
            -7.0f,
            3579545.0
        },
        {
            "sn-psg-coin",
            "Arcade UI",
            "Sega PSG Coin",
            "Bright tone-only arcade pop.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::coin,
            PlayMode::stack,
            { 0.15f, 0.92f, 0.05f, 0.10f },
            { true, false, false, false },
            0.0f,
            0,
            0,
            0,
            -11.0f,
            3579545.0
        },
        {
            "sn-arcade-laser",
            "Arcade UI",
            "Sega PSG Arcade Laser",
            "SN76489 tone sweep with white-noise bite.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::laser,
            PlayMode::stack,
            { 0.20f, 1.00f, 0.70f, 0.95f },
            { true, true, false, true },
            0.0f,
            0,
            0,
            4,
            -11.0f,
            3579545.0
        },
        {
            "sn-noise-hit",
            "SN76489 / Sega PSG",
            "PSG Noise Hit",
            "SN76489 white-noise impact with tone lanes muted.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.20f, 0.15f, 0.82f, 1.0f },
            { false, false, false, true },
            0.0f,
            0,
            0,
            3,
            -12.0f,
            3579545.0
        },
        {
            "nes-thin-duty-pluck",
            "NES Leads",
            "NES Thin Duty Pluck",
            "Short 12.5% pulse pluck for bright melodic hooks.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.0f, 0.22f, 0.04f, 0.70f },
            { true, false, false, false },
            0.62f,
            0,
            0,
            1,
            -11.0f,
            1789773.0
        },
        {
            "nes-duty-arp-runner",
            "NES Leads",
            "NES Duty Arp Runner",
            "Pulse pair and triangle body tuned for fast duty-cycling arps.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.33f, 0.75f, 0.08f, 0.72f },
            { true, true, true, false },
            0.18f,
            0,
            0,
            0,
            -10.0f,
            1789773.0
        },
        {
            "nes-triangle-kick",
            "NES Drums",
            "NES Triangle Kick",
            "Triangle thump with a controlled short-noise click.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.50f, 0.05f, 0.30f, 0.08f },
            { false, false, true, true },
            0.90f,
            0,
            0,
            2,
            -12.0f,
            1789773.0
        },
        {
            "nes-menu-confirm",
            "Arcade UI",
            "NES Menu Confirm",
            "Compact two-pulse UI chirp with quick sweep motion.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::coin,
            PlayMode::stack,
            { 0.67f, 0.78f, 0.02f, 0.88f },
            { true, true, false, false },
            0.42f,
            0,
            0,
            1,
            -11.0f,
            1789773.0
        },
        {
            "dmg-pulse-lead",
            "DMG Pulse",
            "DMG Pulse Lead",
            "Handheld two-pulse lead with stereo split routing.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.67f, 0.35f, 0.12f, 0.78f },
            { true, true, false, false },
            0.20f,
            0,
            0,
            1,
            -10.0f,
            4194304.0,
            0.0f,
            4
        },
        {
            "dmg-wave-glass",
            "DMG Wave",
            "DMG Wave Glass",
            "Bright Wave RAM tone for bell-like handheld melodies.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.46f, 0.18f, 0.08f, 0.78f },
            { false, false, true, false },
            0.18f,
            2,
            0,
            0,
            -11.0f,
            4194304.0,
            0.0f,
            1
        },
        {
            "dmg-noise-kick",
            "DMG Drums",
            "DMG Noise Kick",
            "Short DMG noise thud for compact tracker drums.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.20f, 0.08f, 0.52f, 0.36f },
            { false, false, false, true },
            0.86f,
            0,
            0,
            2,
            -12.0f,
            4194304.0,
            0.0f,
            1
        },
        {
            "dmg-split-chord",
            "DMG Pulse",
            "DMG Split Chord",
            "Pulse and wave stack with split left/right handheld routing.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.58f, 0.64f, 0.12f, 0.82f },
            { true, true, true, false },
            0.12f,
            4,
            0,
            0,
            -10.0f,
            4194304.0,
            0.0f,
            4
        },
        {
            "sid-filter-pluck",
            "SID PWM Leads",
            "SID Filter Pluck",
            "Pulse stack through the SID-style low-pass route for quick C64 plucks.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.42f, 0.22f, 0.25f, 0.35f },
            { true, true, true, false },
            0.62f,
            3,
            1,
            1,
            -10.0f,
            985248.0,
            0.68f,
            1,
            3,
            3,
            1
        },
        {
            "sid-8580-round-bass",
            "SID Bass",
            "SID 8580 Round Bass",
            "Cleaner 8580-style pulse bass with voices 1 and 2 routed into the filter.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::bass,
            PlayMode::stack,
            { 0.54f, 0.12f, 0.32f, 0.84f },
            { true, true, false, false },
            0.34f,
            3,
            1,
            1,
            -8.0f,
            985248.0,
            0.32f,
            2,
            3,
            0,
            5
        },
        {
            "sid-sync-saw-lead",
            "SID FX",
            "SID Sync Saw Lead",
            "Saw-led SID stack with sync-style control bits for sharper motion.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.36f, 0.58f, 0.62f, 0.64f },
            { true, true, true, false },
            0.22f,
            2,
            3,
            2,
            -11.0f,
            985248.0,
            0.45f,
            1,
            3,
            1,
            1
        },
        {
            "sid-ring-bell",
            "SID FX",
            "SID Ring Bell",
            "Triangle/pulse SID voice mix using ring-style control bits and band-pass filtering.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.50f, 0.46f, 0.48f, 0.58f },
            { true, true, true, false },
            0.46f,
            1,
            2,
            3,
            -12.0f,
            985248.0,
            0.60f,
            1,
            1,
            3,
            1
        },
        {
            "sid-noise-riser",
            "SID FX",
            "SID Noise Riser",
            "Filtered voice-3 noise with sync/ring grit for risers and impacts.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::laser,
            PlayMode::stack,
            { 0.50f, 0.84f, 0.76f, 0.30f },
            { false, true, true, false },
            0.88f,
            2,
            2,
            4,
            -12.0f,
            985248.0,
            0.85f,
            2,
            2,
            4,
            4
        },
        {
            "sid-notch-pwm-keys",
            "SID PWM Leads",
            "SID Notch PWM Keys",
            "Pulse-stack keys using SID LP+HP notch bits with tight per-voice ADSR.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.62f, 0.33f, 0.55f, 0.64f },
            { true, true, true, false },
            0.42f,
            3,
            5,
            1,
            -10.0f,
            985248.0,
            0.52f,
            1,
            3,
            2,
            1,
            1,
            8,
            7,
            4,
            1,
            8,
            7,
            4,
            1,
            6,
            5,
            3,
            0.92f,
            0.78f,
            0.55f,
            1.0f
        },
        {
            "sid-lpbp-sweep-stack",
            "SID FX",
            "SID LP+BP Sweep Stack",
            "Saw/pulse stack through combined LP+BP filter bits for sweepable C64 leads.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::powerUp,
            PlayMode::stack,
            { 0.46f, 0.72f, 0.66f, 0.62f },
            { true, true, true, false },
            0.36f,
            2,
            6,
            2,
            -11.0f,
            985248.0,
            0.70f,
            2,
            3,
            1,
            1,
            2,
            9,
            10,
            5,
            2,
            8,
            9,
            5,
            1,
            7,
            8,
            4,
            0.88f,
            0.62f,
            0.45f,
            1.0f
        },
        {
            "sid-bphp-metal-bell",
            "SID FX",
            "SID BP+HP Metal Bell",
            "Ring-mod triangle/pulse stack through BP+HP filter bits with staggered ADSR.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.50f, 0.56f, 0.50f, 0.48f },
            { true, true, true, false },
            0.50f,
            1,
            7,
            3,
            -12.0f,
            985248.0,
            0.68f,
            1,
            3,
            1,
            1,
            1,
            6,
            3,
            8,
            1,
            7,
            4,
            9,
            1,
            8,
            5,
            10,
            0.65f,
            0.90f,
            0.52f,
            1.0f
        },
        {
            "sid-allmode-growl",
            "SID Bass",
            "SID All-Mode Growl",
            "Pulse, saw, and noise voices summed through all SID filter output bits.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::bass,
            PlayMode::stack,
            { 0.40f, 0.30f, 0.42f, 0.88f },
            { true, true, true, false },
            0.30f,
            3,
            8,
            4,
            -12.0f,
            985248.0,
            0.80f,
            1,
            2,
            4,
            1,
            1,
            5,
            13,
            4,
            1,
            6,
            12,
            4,
            1,
            4,
            7,
            3,
            0.82f,
            0.58f,
            0.36f,
            1.0f
        },
        {
            "ym-bright-beep",
            "YM Beeps",
            "YM Bright Beep",
            "Single-channel AY/YM tone beep for menus and alerts.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::coin,
            PlayMode::stack,
            { 0.18f, 0.72f, 0.06f, 0.50f },
            { true, false, false, false },
            0.0f,
            0,
            0,
            0,
            -11.0f,
            2000000.0
        },
        {
            "ym-envelope-bell",
            "YM Beeps",
            "YM Envelope Bell",
            "Hardware-envelope-style triangle shape over three bright PSG tones.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.62f, 0.22f, 0.18f, 0.66f },
            { true, true, true, false },
            0.48f,
            0,
            4,
            0,
            -9.0f,
            2000000.0
        },
        {
            "ym-arcade-clang",
            "Classic Game SFX",
            "YM Arcade Clang",
            "Tone plus shared noise impact with a rising hardware envelope.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::hit,
            PlayMode::stack,
            { 0.42f, 0.34f, 0.76f, 0.96f },
            { true, true, false, true },
            0.55f,
            0,
            2,
            0,
            -12.0f,
            2000000.0
        },
        {
            "ym-fast-minor-arp",
            "YM Arps",
            "YM Fast Minor Arp",
            "Three-channel fake minor chord with tight demo-scene motion.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.82f, 0.86f, 0.10f, 0.54f },
            { true, true, true, false },
            0.0f,
            0,
            0,
            0,
            -10.0f,
            2000000.0
        },
        {
            "sn-tone-stack",
            "SN76489 / Sega PSG",
            "PSG Tone Stack",
            "Three SN76489 tone lanes stacked for bright Sega-style leads.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.78f, 0.34f, 0.08f, 0.12f },
            { true, true, true, false },
            0.0f,
            0,
            0,
            0,
            -7.0f,
            3579545.0
        },
        {
            "sn-arcade-bass",
            "SN76489 / Sega PSG",
            "PSG Arcade Bass",
            "Low square-wave bass centered on the first PSG tone channel.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::bass,
            PlayMode::stack,
            { 0.36f, 0.12f, 0.04f, 0.08f },
            { true, false, false, false },
            0.0f,
            0,
            0,
            0,
            -8.0f,
            3579545.0
        },
        {
            "sn-periodic-zap",
            "Classic Game SFX",
            "PSG Periodic Zap",
            "SN76489 periodic-noise zap paired with a tone sweep.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::laser,
            PlayMode::stack,
            { 0.28f, 0.88f, 0.52f, 0.78f },
            { true, false, false, true },
            0.0f,
            0,
            0,
            2,
            -11.0f,
            3579545.0
        },
        {
            "sn-warning-alarm",
            "Arcade UI",
            "PSG Warning Alarm",
            "Two-tone PSG warning chirp with a white-noise edge.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::jump,
            PlayMode::stack,
            { 0.64f, 0.70f, 0.82f, 0.42f },
            { true, true, false, true },
            0.0f,
            0,
            0,
            4,
            -11.0f,
            3579545.0
        }
    };

    return presets;
}

std::vector<const PresetInfo*> presetsForChip(ChipMode chip)
{
    std::vector<const PresetInfo*> matches;
    for (const auto& preset : presetCatalog())
    {
        if (preset.chip == chip)
            matches.push_back(&preset);
    }

    return matches;
}

const PresetInfo* presetById(std::string_view idOrName)
{
    const auto key = presetKey(idOrName);
    const auto& presets = presetCatalog();
    const auto iter = std::find_if(presets.begin(), presets.end(), [&key](const auto& preset)
    {
        return presetKey(preset.id) == key || presetKey(preset.name) == key;
    });

    return iter != presets.end() ? &*iter : nullptr;
}

PatchConfig patchConfigForPreset(const PresetInfo& preset)
{
    return makePatchConfig(preset.chip,
                           preset.macro,
                           preset.controls[0],
                           preset.controls[1],
                           preset.controls[2],
                           preset.controls[3],
                           preset.playMode,
                           preset.sourceEnabled,
                           { preset.source1Level, preset.source2Level, preset.source3Level, preset.source4Level },
                           preset.stereoSpread,
                           preset.envelopeDecay,
                           preset.waveShape,
                           0,
                           0,
                           preset.dmgStereoRoute,
                           preset.ymEnvelopeShape,
                           0,
                           0,
                           0,
                           preset.snNoiseMode,
                           preset.sidVoice2WaveShape,
                           preset.sidVoice3WaveShape,
                           preset.sidAttack,
                           preset.sidDecay,
                           preset.sidSustain,
                           preset.sidRelease,
                           preset.sidVoice2Attack,
                           preset.sidVoice2Decay,
                           preset.sidVoice2Sustain,
                           preset.sidVoice2Release,
                           preset.sidVoice3Attack,
                           preset.sidVoice3Decay,
                           preset.sidVoice3Sustain,
                           preset.sidVoice3Release,
                           preset.sidFilterRouting);
}

} // namespace chipper
