#include "Presets.h"

#include "Engine/ChipDescriptors.h"

#include <algorithm>
#include <cctype>

namespace chipper
{
namespace
{

std::string presetKey(std::string_view text)
{
    std::string key(text.begin(), text.end());
    std::transform(key.begin(), key.end(), key.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    key.erase(std::remove_if(key.begin(), key.end(), [](char c) { return c == '_' || c == '-' || c == '/' || c == ' '; }), key.end());
    return key;
}

PresetInfo withSourceLevels(PresetInfo preset, float source1, float source2, float source3, float source4)
{
    preset.source1Level = source1;
    preset.source2Level = source2;
    preset.source3Level = source3;
    preset.source4Level = source4;
    return preset;
}

PresetInfo withDmgWaveLevel(PresetInfo preset, int waveLevel)
{
    preset.dmgWaveLevel = waveLevel;
    return preset;
}

PresetInfo withNesDmcDirect(PresetInfo preset, float level)
{
    preset.nesDmcDirectLevel = level;
    return preset;
}

} // namespace

const std::vector<PresetInfo>& presetCatalog()
{
    static const std::vector<PresetInfo> presets {
        {
            "nes-hero-pulse",
            "NES Leads",
            "NES Hero Pulse",
            "Forward pulse lead with pulse stack and triangle support.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.67f, 0.38f, 0.12f, 0.78f },
            { true, true, true, false },
            0.0f,
            0,
            0,
            0,
            -9.0f,
            1789773.0
        },
        {
            "nes-triangle-bass",
            "NES Bass",
            "NES Triangle Bass",
            "Triangle-weighted bass with restrained pulse support.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::bass,
            PlayMode::stack,
            { 0.50f, 0.16f, 0.05f, 0.12f },
            { true, false, true, false },
            0.0f,
            0,
            0,
            0,
            -8.0f,
            1789773.0
        },
        withNesDmcDirect({
            "nes-noise-snare",
            "NES Drums",
            "NES Noise Snare",
            "Short RP2A03 noise burst with triangle transient.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.33f, 0.12f, 0.86f, 0.42f },
            { false, false, true, true },
            0.78f,
            0,
            0,
            0,
            -10.0f,
            1789773.0
        }, 0.34f),
        {
            "nes-coin-blip",
            "Arcade UI",
            "NES Coin Blip",
            "Bright short pulse pop for UI and pickup sounds.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::coin,
            PlayMode::stack,
            { 0.16f, 0.90f, 0.06f, 0.82f },
            { true, true, false, false },
            0.45f,
            0,
            0,
            0,
            -11.0f,
            1789773.0
        },
        withNesDmcDirect({
            "nes-boss-damage",
            "Classic Game SFX",
            "NES Boss Damage",
            "Noisy RP2A03 impact with triangle thump and one pulse edge.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::hit,
            PlayMode::stack,
            { 0.45f, 0.25f, 0.76f, 0.64f },
            { true, false, true, true },
            0.60f,
            0,
            0,
            2,
            -12.0f,
            1789773.0
        }, 0.66f),
        {
            "nes-power-up-rise",
            "Classic Game SFX",
            "NES Power-Up Rise",
            "Optimistic RP2A03 pulse stack with triangle lift.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::powerUp,
            PlayMode::stack,
            { 0.70f, 0.90f, 0.20f, 0.90f },
            { true, true, true, false },
            0.0f,
            0,
            0,
            0,
            -10.0f,
            1789773.0
        },
        {
            "dmg-wave-bass",
            "DMG Wave",
            "DMG Wave Bass",
            "Wave-channel bass body using a written triangle table.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::bass,
            PlayMode::stack,
            { 0.50f, 0.18f, 0.08f, 0.92f },
            { false, false, true, false },
            0.0f,
            1,
            0,
            0,
            -8.0f,
            4194304.0,
            0.0f,
            1
        },
        {
            "dmg-pocket-arp",
            "DMG Pulse",
            "DMG Pocket Arp",
            "Pulse and wave stack arranged for fast handheld arps.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.66f, 0.78f, 0.18f, 0.72f },
            { true, true, true, false },
            0.0f,
            4,
            0,
            0,
            -10.0f,
            4194304.0,
            0.0f,
            4
        },
        {
            "dmg-noise-hat",
            "DMG Drums",
            "DMG Noise Hat",
            "Narrow polynomial-noise percussion with short hardware decay.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.20f, 0.12f, 0.96f, 0.74f },
            { false, false, false, true },
            0.88f,
            0,
            0,
            0,
            -12.0f,
            4194304.0,
            0.0f,
            1
        },
        {
            "dmg-power-up-rise",
            "Classic Game SFX",
            "DMG Power-Up Rise",
            "Handheld pulse and wave stack for rising pickup gestures.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::powerUp,
            PlayMode::stack,
            { 0.70f, 0.90f, 0.18f, 0.86f },
            { true, true, true, false },
            0.0f,
            2,
            0,
            0,
            -10.0f,
            4194304.0,
            0.0f,
            4
        },
        {
            "sid-dirty-bass",
            "SID Bass",
            "SID Dirty Bass",
            "Dual pulse-voice C64 bass using SID pulse-width and sustain registers.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::bass,
            PlayMode::stack,
            { 0.48f, 0.18f, 0.40f, 0.82f },
            { true, true, false, false },
            0.28f,
            3,
            1,
            1,
            -9.0f,
            985248.0,
            0.58f,
            1,
            3,
            0,
            5
        },
        {
            "sid-pwm-lead",
            "SID PWM Leads",
            "SID PWM Lead",
            "Three SID voices stacked around pulse waveform control and voice detune.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.58f, 0.40f, 0.72f, 0.70f },
            { true, true, true, false },
            0.32f,
            3,
            1,
            1,
            -10.0f,
            985248.0,
            0.36f,
            2,
            3,
            3,
            1
        },
        {
            "sid-robot-arp",
            "SID FX",
            "SID Robot Arp",
            "Mixed saw, pulse, and triangle SID stack for robotic arps and tight pattern movement.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.50f, 0.78f, 0.85f, 0.60f },
            { true, true, true, false },
            0.25f,
            2,
            2,
            1,
            -10.0f,
            985248.0,
            0.42f,
            2,
            3,
            1,
            1
        },
        {
            "sid-noise-drum",
            "SID FX",
            "SID Noise Drum",
            "Noise waveform on SID voice 3 with a fast ADSR-style decay.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.50f, 0.10f, 0.80f, 0.20f },
            { false, false, true, false },
            0.95f,
            4,
            1,
            1,
            -12.0f,
            985248.0,
            0.18f,
            1,
            0,
            4,
            4
        },
        {
            "ym-three-voice-arp",
            "YM Arps",
            "YM Three-Voice Arp",
            "A/B/C fake-chord spread for demo-scene arpeggios.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.70f, 0.70f, 0.12f, 0.52f },
            { true, true, true, false },
            0.0f,
            0,
            0,
            0,
            -10.0f,
            2000000.0
        },
        {
            "ym-fake-chord-stack",
            "YM Arps",
            "YM Fake Chord Stack",
            "Three YM/AY tone channels voiced as a bright fake chord.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::stack,
            { 0.95f, 0.76f, 0.12f, 0.50f },
            { true, true, true, false },
            0.0f,
            0,
            0,
            0,
            -10.0f,
            2000000.0
        },
        {
            "ym-menu-beep",
            "YM Beeps",
            "YM Menu Beep",
            "Single-channel square beep with bright pitch gesture.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::coin,
            PlayMode::stack,
            { 0.15f, 0.82f, 0.08f, 0.50f },
            { true, false, false, false },
            0.0f,
            0,
            0,
            0,
            -9.0f,
            2000000.0
        },
        {
            "ym-noise-hat",
            "YM Noise Percussion",
            "YM Noise Hat",
            "Shared-noise percussion through channel A.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.25f, 0.10f, 0.92f, 0.18f },
            { true, false, false, true },
            0.0f,
            0,
            1,
            0,
            -12.0f,
            2000000.0
        },
        {
            "sn-psg-lead",
            "SN76489 / Sega PSG",
            "Sega PSG Lead",
            "Forward tone-channel lead across the SN76489 tone lanes.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.52f, 0.45f, 0.12f, 0.22f },
            { true, true, true, false },
            0.0f,
            0,
            0,
            0,
            -7.0f,
            3579545.0
        },
        {
            "sn-psg-coin",
            "Arcade UI",
            "Sega PSG Coin",
            "Bright tone-only arcade pop.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::coin,
            PlayMode::stack,
            { 0.15f, 0.92f, 0.05f, 0.10f },
            { true, false, false, false },
            0.0f,
            0,
            0,
            0,
            -11.0f,
            3579545.0
        },
        {
            "sn-arcade-laser",
            "Arcade UI",
            "Sega PSG Arcade Laser",
            "SN76489 tone sweep with white-noise bite.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::laser,
            PlayMode::stack,
            { 0.20f, 1.00f, 0.70f, 0.95f },
            { true, true, false, true },
            0.0f,
            0,
            0,
            4,
            -11.0f,
            3579545.0
        },
        {
            "sn-noise-hit",
            "SN76489 / Sega PSG",
            "PSG Noise Hit",
            "SN76489 white-noise impact with tone lanes muted.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.20f, 0.15f, 0.82f, 1.0f },
            { false, false, false, true },
            0.0f,
            0,
            0,
            3,
            -12.0f,
            3579545.0
        },
        {
            "pokey-buzzy-lead",
            "Atari POKEY",
            "POKEY Buzzy Lead",
            "Forward four-channel Atari lead with polynomial edge.",
            ChipMode::pokey,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.68f, 0.42f, 0.40f, 0.72f },
            { true, true, true, false },
            0.10f,
            2,
            0,
            0,
            -9.0f,
            1789790.0,
            0.18f
        },
        withSourceLevels(
            {
                "pokey-distortion-bass",
                "Atari POKEY",
                "POKEY Distortion Bass",
                "Low two-channel Atari bass with AUDC-style distortion color.",
                ChipMode::pokey,
                AccuracyMode::hybrid,
                MacroKind::bass,
                PlayMode::stack,
                { 0.32f, 0.22f, 0.28f, 0.68f },
                { true, true, false, false },
                0.08f,
                1,
                0,
                0,
                -8.0f,
                1789790.0
            },
            1.0f,
            0.64f,
            1.0f,
            1.0f),
        {
            "pokey-four-channel-arp",
            "Atari POKEY",
            "POKEY Four-Channel Arp",
            "Four POKEY timers spread into a bright fake chord.",
            ChipMode::pokey,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.82f, 0.70f, 0.25f, 0.62f },
            { true, true, true, true },
            0.08f,
            1,
            0,
            0,
            -10.0f,
            1789790.0,
            0.35f
        },
        {
            "pokey-poly-perc",
            "Atari POKEY",
            "POKEY Poly Perc",
            "Short POKEY polynomial percussion using channels 3 and 4.",
            ChipMode::pokey,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.28f, 0.18f, 0.88f, 0.82f },
            { false, false, true, true },
            0.80f,
            4,
            0,
            0,
            -12.0f,
            1789790.0
        },
        {
            "huc-glass-lead",
            "PC Engine HuC6280",
            "HuC6280 Glass Lead",
            "Bright PC Engine wavetable lead using a shaped 32-sample wave.",
            ChipMode::huc6280,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.64f, 0.42f, 0.18f, 0.76f },
            { true, true, true, false },
            0.10f,
            1,
            0,
            0,
            -9.0f,
            3579545.0,
            0.20f
        },
        withSourceLevels(
            {
                "huc-wave-bass",
                "PC Engine HuC6280",
                "HuC6280 Wave Bass",
                "Low rounded wavetable bass with two-channel body.",
                ChipMode::huc6280,
                AccuracyMode::hybrid,
                MacroKind::bass,
                PlayMode::stack,
                { 0.30f, 0.20f, 0.12f, 0.82f },
                { true, true, false, false },
                0.08f,
                2,
                0,
                0,
                -8.0f,
                3579545.0
            },
            1.0f,
            0.64f,
            1.0f,
            1.0f),
        {
            "huc-six-wave-arp",
            "PC Engine HuC6280",
            "HuC6280 Six-Wave Arp",
            "Stacked wavetable channels for fake PC Engine chords and fast patterns.",
            ChipMode::huc6280,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.88f, 0.70f, 0.14f, 0.70f },
            { true, true, true, true },
            0.08f,
            0,
            0,
            0,
            -10.0f,
            3579545.0,
            0.35f
        },
        {
            "huc-noise-tap",
            "PC Engine HuC6280",
            "HuC6280 Noise Tap",
            "Short wavetable/noise percussion using the HuC6280 noise-control path.",
            ChipMode::huc6280,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.32f, 0.18f, 0.88f, 0.80f },
            { false, false, true, true },
            0.72f,
            4,
            0,
            0,
            -12.0f,
            3579545.0
        },
        {
            "scc-arcade-lead",
            "Konami SCC",
            "SCC Arcade Lead",
            "Forward Konami-style wavetable lead using a bright 32-byte ramp.",
            ChipMode::scc,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.54f, 0.42f, 0.32f, 0.80f },
            { true, true, true, false },
            0.10f,
            1,
            0,
            0,
            -9.0f,
            3579545.0,
            0.18f
        },
        withSourceLevels(
            {
                "scc-wave-bass",
                "Konami SCC",
                "SCC Wave Bass",
                "Rounded SCC bass with a detuned second wavetable voice.",
                ChipMode::scc,
                AccuracyMode::hybrid,
                MacroKind::bass,
                PlayMode::stack,
                { 0.26f, 0.24f, 0.28f, 0.84f },
                { true, true, false, false },
                0.08f,
                2,
                0,
                0,
                -8.5f,
                3579545.0
            },
            1.0f,
            0.58f,
            1.0f,
            1.0f),
        {
            "scc-five-voice-arp",
            "Konami SCC",
            "SCC Five-Voice Arp",
            "Crunchy wavetable fake chord/arpeggio stack with channel 5 participating internally.",
            ChipMode::scc,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.88f, 0.72f, 0.34f, 0.76f },
            { true, true, true, true },
            0.08f,
            0,
            0,
            0,
            -10.0f,
            3579545.0,
            0.32f
        },
        {
            "scc-wave-tick",
            "Konami SCC",
            "SCC Wave Tick",
            "Short stepped-wave percussion from SCC wave RAM.",
            ChipMode::scc,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.30f, 0.18f, 0.86f, 0.82f },
            { false, false, true, true },
            0.66f,
            4,
            0,
            0,
            -12.0f,
            3579545.0
        },
        {
            "namco-arcade-lead",
            "Namco WSG",
            "Namco Arcade Lead",
            "Bright 4-bit arcade wavetable lead.",
            ChipMode::namcoWsg,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.56f, 0.42f, 0.32f, 0.80f },
            { true, true, true, false },
            0.10f,
            1,
            0,
            0,
            -9.0f,
            96000.0,
            0.18f
        },
        withSourceLevels(
            {
                "namco-wave-bass",
                "Namco WSG",
                "Namco Wave Bass",
                "Rounded arcade wavetable bass with a low octave layer.",
                ChipMode::namcoWsg,
                AccuracyMode::hybrid,
                MacroKind::bass,
                PlayMode::stack,
                { 0.28f, 0.22f, 0.24f, 0.84f },
                { true, true, false, false },
                0.08f,
                2,
                0,
                0,
                -8.5f,
                96000.0
            },
            1.0f,
            0.58f,
            1.0f,
            1.0f),
        {
            "namco-tracker-arp",
            "Namco WSG",
            "Namco Tracker Arp",
            "Fast multi-lane arcade wavetable arp.",
            ChipMode::namcoWsg,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.90f, 0.72f, 0.36f, 0.76f },
            { true, true, true, true },
            0.08f,
            0,
            0,
            0,
            -10.0f,
            96000.0,
            0.32f
        },
        {
            "namco-wave-tick",
            "Namco WSG",
            "Namco Wave Tick",
            "Short stepped-wave arcade percussion.",
            ChipMode::namcoWsg,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.30f, 0.20f, 0.86f, 0.82f },
            { false, false, true, true },
            0.66f,
            4,
            0,
            0,
            -12.0f,
            96000.0
        },
        withSourceLevels(
            {
                "opn2-feedback-bass",
                "YM2612 / OPN2",
                "OPN2 Feedback Bass",
                "Genesis-style feedback bass using ymfm-backed YM2612 algorithm and operator writes.",
                ChipMode::ym2612,
                AccuracyMode::hybrid,
                MacroKind::bass,
                PlayMode::stack,
                { 0.00f, 0.82f, 0.28f, 0.88f },
                { true, true, false, false },
                0.08f,
                1,
                0,
                0,
                -9.0f,
                7670454.0
            },
            1.0f,
            0.45f,
            1.0f,
            1.0f),
        {
            "opn2-metallic-lead",
            "YM2612 / OPN2",
            "OPN2 Metallic Lead",
            "Bright Genesis FM lead with parallel carrier bite.",
            ChipMode::ym2612,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.58f, 0.44f, 0.62f, 0.82f },
            { true, true, true, false },
            0.10f,
            5,
            0,
            0,
            -9.5f,
            7670454.0
        },
        {
            "opn2-fake-chord-arp",
            "YM2612 / OPN2",
            "OPN2 Fake Chord Arp",
            "Four exposed YM2612 lanes arranged for playable chip-poly arpeggios.",
            ChipMode::ym2612,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.72f, 0.32f, 0.50f, 0.78f },
            { true, true, true, true },
            0.08f,
            6,
            0,
            0,
            -10.5f,
            7670454.0
        },
        {
            "opn2-ui-chime",
            "Arcade UI",
            "OPN2 UI Chime",
            "Short additive-FM chime for menu and pickup sounds.",
            ChipMode::ym2612,
            AccuracyMode::hybrid,
            MacroKind::coin,
            PlayMode::stack,
            { 1.00f, 0.18f, 0.70f, 0.76f },
            { true, false, false, false },
            0.16f,
            8,
            0,
            0,
            -11.0f,
            7670454.0
        },
        {
            "opn2-damage-hit",
            "Classic Game SFX",
            "OPN2 Damage Hit",
            "Aggressive stacked FM impact with high feedback.",
            ChipMode::ym2612,
            AccuracyMode::hybrid,
            MacroKind::hit,
            PlayMode::stack,
            { 0.22f, 0.90f, 0.75f, 0.78f },
            { true, false, true, true },
            0.55f,
            2,
            0,
            0,
            -11.0f,
            7670454.0
        },
        {
            "opn2-pitch-laser",
            "Classic Game SFX",
            "OPN2 Pitch Laser",
            "Register-backed YM2612 pitch-sweep SFX gesture.",
            ChipMode::ym2612,
            AccuracyMode::hybrid,
            MacroKind::laser,
            PlayMode::stack,
            { 0.30f, 0.72f, 0.88f, 0.80f },
            { true, true, false, true },
            0.28f,
            3,
            0,
            0,
            -11.5f,
            7670454.0
        },
        {
            "opn2-power-rise",
            "Modern Chip Hybrid",
            "OPN2 Power Rise",
            "Longer Genesis FM rise using stacked melodic lanes.",
            ChipMode::ym2612,
            AccuracyMode::hybrid,
            MacroKind::powerUp,
            PlayMode::stack,
            { 0.86f, 0.36f, 0.58f, 0.84f },
            { true, true, true, true },
            0.14f,
            7,
            0,
            0,
            -10.0f,
            7670454.0
        },
        withSourceLevels(
            {
                "opl2-bass",
                "OPL2/OPL3 / DOS FM",
                "OPL2 Bass",
                "Rounded ymfm-backed two-operator DOS FM bass.",
                ChipMode::opl3,
                AccuracyMode::hybrid,
                MacroKind::bass,
                PlayMode::stack,
                { 0.20f, 0.62f, 0.25f, 0.88f },
                { true, true, false, false },
                0.08f,
                1,
                0,
                0,
                -9.0f,
                3579545.0
            },
            1.0f,
            0.45f,
            1.0f,
            1.0f),
        {
            "opl2-bright-lead",
            "OPL2/OPL3 / DOS FM",
            "OPL2 Bright Lead",
            "Bright DOS FM lead using native OPL2 waveform registers.",
            ChipMode::opl3,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.70f, 0.42f, 0.72f, 0.82f },
            { true, true, true, false },
            0.10f,
            4,
            0,
            0,
            -9.5f,
            3579545.0
        },
        {
            "opl2-organ-arp",
            "OPL2/OPL3 / DOS FM",
            "OPL2 Organ Arp",
            "Four exposed OPL melodic lanes arranged for fake chords.",
            ChipMode::opl3,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.78f, 0.28f, 0.48f, 0.78f },
            { true, true, true, true },
            0.08f,
            2,
            0,
            0,
            -10.0f,
            3579545.0
        },
        {
            "opl2-ui-bell",
            "Arcade UI",
            "OPL2 UI Bell",
            "Short DOS FM bell for menu and pickup sounds.",
            ChipMode::opl3,
            AccuracyMode::hybrid,
            MacroKind::coin,
            PlayMode::stack,
            { 0.85f, 0.20f, 0.55f, 0.78f },
            { true, false, false, false },
            0.16f,
            3,
            0,
            0,
            -11.0f,
            3579545.0
        },
        {
            "opl2-laser",
            "Classic Game SFX",
            "OPL2 Laser",
            "Pitch-swept DOS FM SFX gesture.",
            ChipMode::opl3,
            AccuracyMode::hybrid,
            MacroKind::laser,
            PlayMode::stack,
            { 0.32f, 0.72f, 0.90f, 0.80f },
            { true, true, false, true },
            0.28f,
            4,
            0,
            0,
            -11.5f,
            3579545.0
        },
        {
            "opll-ui-chime",
            "YM2413 / OPLL",
            "OPLL UI Chime",
            "Bright preset-FM chime using emu2413-backed YM2413 melodic registers.",
            ChipMode::ym2413,
            AccuracyMode::hybrid,
            MacroKind::coin,
            PlayMode::stack,
            { 0.80f, 0.72f, 0.22f, 0.78f },
            { true, false, false, false },
            0.18f,
            1,
            0,
            0,
            -10.0f,
            3579545.0,
            0.0f
        },
        withSourceLevels(
            {
                "opll-preset-bass",
                "YM2413 / OPLL",
                "OPLL Preset Bass",
                "Rounded YM2413 preset-FM bass with a quiet octave layer.",
                ChipMode::ym2413,
                AccuracyMode::hybrid,
                MacroKind::bass,
                PlayMode::stack,
                { 0.85f, 0.22f, 0.16f, 0.86f },
                { true, true, false, false },
                0.08f,
                2,
                0,
                0,
                -8.5f,
                3579545.0
            },
            1.0f,
            0.55f,
            1.0f,
            1.0f),
        {
            "opll-brass-lead",
            "YM2413 / OPLL",
            "OPLL Brass Lead",
            "Forward OPLL lead using native preset instrument, f-number, block, and key-on writes.",
            ChipMode::ym2413,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.45f, 0.48f, 0.24f, 0.80f },
            { true, true, true, false },
            0.10f,
            3,
            0,
            0,
            -9.0f,
            3579545.0,
            0.0f
        },
        {
            "opll-organ-arp",
            "YM2413 / OPLL",
            "OPLL Organ Arp",
            "Four exposed OPLL melodic channels arranged for fast organ-like fake chords.",
            ChipMode::ym2413,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.55f, 0.70f, 0.18f, 0.78f },
            { true, true, true, true },
            0.08f,
            4,
            0,
            0,
            -10.0f,
            3579545.0,
            0.0f
        },
        withSourceLevels(
            {
                "spc700-soft-bass",
                "SNES SPC700-style",
                "SPC700 Soft Bass",
                "Rounded low lo-fi sample bass with subtle echo color.",
                ChipMode::spc700,
                AccuracyMode::hybrid,
                MacroKind::bass,
                PlayMode::stack,
                { 0.30f, 0.24f, 0.26f, 0.84f },
                { true, true, false, false },
                0.10f,
                2,
                0,
                0,
                -9.0f,
                32000.0,
                0.40f
            },
            1.0f,
            0.62f,
            1.0f,
            1.0f),
        {
            "spc700-bell-lead",
            "SNES SPC700-style",
            "SPC700 Bell Lead",
            "Bright lo-fi sample lead with soft SNES-style body.",
            ChipMode::spc700,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.58f, 0.46f, 0.30f, 0.80f },
            { true, true, true, false },
            0.12f,
            1,
            0,
            0,
            -10.0f,
            32000.0,
            0.50f
        },
        {
            "spc700-voice-arp",
            "SNES SPC700-style",
            "SPC700 Voice Arp",
            "Stacked sample voices for quick SNES-style arps and fake chords.",
            ChipMode::spc700,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.86f, 0.70f, 0.28f, 0.76f },
            { true, true, true, true },
            0.10f,
            1,
            0,
            0,
            -10.0f,
            32000.0,
            0.70f
        },
        {
            "spc700-drum-map",
            "SNES SPC700-style",
            "SPC700 Drum Map",
            "Short lo-fi noise sample percussion with SNES-style softness.",
            ChipMode::spc700,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.30f, 0.20f, 0.10f, 0.82f },
            { false, false, true, true },
            0.68f,
            4,
            0,
            0,
            -12.0f,
            32000.0,
            0.55f
        },
        withSourceLevels(
            {
                "paula-tracker-bass",
                "Amiga Paula",
                "Paula Tracker Bass",
                "Looped 8-bit triangle sample bass with a second-channel body.",
                ChipMode::paula,
                AccuracyMode::hybrid,
                MacroKind::bass,
                PlayMode::stack,
                { 0.30f, 0.26f, 0.60f, 0.84f },
                { true, true, false, false },
                0.08f,
                2,
                0,
                0,
                -9.0f,
                3546895.0,
                0.55f
            },
            1.0f,
            0.58f,
            1.0f,
            1.0f),
        {
            "paula-chip-lead",
            "Amiga Paula",
            "Paula Chip Lead",
            "Bright ramp-sample tracker lead with four-channel spread available.",
            ChipMode::paula,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.58f, 0.46f, 0.55f, 0.80f },
            { true, true, true, false },
            0.10f,
            1,
            0,
            0,
            -10.0f,
            3546895.0,
            0.50f
        },
        {
            "paula-tracker-arp",
            "Amiga Paula",
            "Paula Tracker Arp",
            "Four-channel Amiga-style sample arp for fast patterns and fake chords.",
            ChipMode::paula,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.86f, 0.70f, 0.58f, 0.76f },
            { true, true, true, true },
            0.08f,
            1,
            0,
            0,
            -10.0f,
            3546895.0,
            0.75f
        },
        {
            "paula-noise-tick",
            "Amiga Paula",
            "Paula Noise Tick",
            "Short decaying 8-bit noise sample percussion.",
            ChipMode::paula,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.30f, 0.20f, 0.12f, 0.82f },
            { false, false, true, true },
            0.66f,
            4,
            0,
            0,
            -12.0f,
            3546895.0,
            0.70f
        },
        {
            "nes-thin-duty-pluck",
            "NES Leads",
            "NES Thin Duty Pluck",
            "Short 12.5% pulse pluck for bright melodic hooks.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.0f, 0.22f, 0.04f, 0.70f },
            { true, false, false, false },
            0.62f,
            0,
            0,
            1,
            -11.0f,
            1789773.0
        },
        {
            "nes-duty-arp-runner",
            "NES Leads",
            "NES Duty Arp Runner",
            "Pulse pair and triangle body tuned for fast duty-cycling arps.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.33f, 0.75f, 0.08f, 0.72f },
            { true, true, true, false },
            0.18f,
            0,
            0,
            0,
            -10.0f,
            1789773.0
        },
        {
            "nes-triangle-kick",
            "NES Drums",
            "NES Triangle Kick",
            "Triangle thump with a controlled short-noise click.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.50f, 0.05f, 0.30f, 0.08f },
            { false, false, true, true },
            0.90f,
            0,
            0,
            2,
            -12.0f,
            1789773.0
        },
        {
            "nes-menu-confirm",
            "Arcade UI",
            "NES Menu Confirm",
            "Compact two-pulse UI chirp with quick sweep motion.",
            ChipMode::nes,
            AccuracyMode::hybrid,
            MacroKind::coin,
            PlayMode::stack,
            { 0.67f, 0.78f, 0.02f, 0.88f },
            { true, true, false, false },
            0.42f,
            0,
            0,
            1,
            -11.0f,
            1789773.0
        },
        withSourceLevels(
            {
                "nes-duty-bass-duo",
                "NES Bass",
                "NES Duty Bass Duo",
                "Triangle-weighted bass with two quiet duty pulses for bite and chord hints.",
                ChipMode::nes,
                AccuracyMode::hybrid,
                MacroKind::bass,
                PlayMode::stack,
                { 0.33f, 0.18f, 0.04f, 0.30f },
                { true, true, true, false },
                0.08f,
                0,
                0,
                0,
                -9.0f,
                1789773.0
            },
            0.52f,
            0.38f,
            1.0f,
            1.0f),
        {
            "dmg-pulse-lead",
            "DMG Pulse",
            "DMG Pulse Lead",
            "Handheld two-pulse lead with stereo split routing.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.67f, 0.35f, 0.12f, 0.78f },
            { true, true, false, false },
            0.20f,
            0,
            0,
            1,
            -10.0f,
            4194304.0,
            0.0f,
            4
        },
        {
            "dmg-wave-glass",
            "DMG Wave",
            "DMG Wave Glass",
            "Bright Wave RAM tone for bell-like handheld melodies.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.46f, 0.18f, 0.08f, 0.78f },
            { false, false, true, false },
            0.18f,
            2,
            0,
            0,
            -11.0f,
            4194304.0,
            0.0f,
            1
        },
        {
            "dmg-noise-kick",
            "DMG Drums",
            "DMG Noise Kick",
            "Short DMG noise thud for compact tracker drums.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::drum,
            PlayMode::stack,
            { 0.20f, 0.08f, 0.52f, 0.36f },
            { false, false, false, true },
            0.86f,
            0,
            0,
            2,
            -12.0f,
            4194304.0,
            0.0f,
            1
        },
        {
            "dmg-split-chord",
            "DMG Pulse",
            "DMG Split Chord",
            "Pulse and wave stack with split left/right handheld routing.",
            ChipMode::dmg,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.58f, 0.64f, 0.12f, 0.82f },
            { true, true, true, false },
            0.12f,
            4,
            0,
            0,
            -10.0f,
            4194304.0,
            0.0f,
            4
        },
        withDmgWaveLevel(
            withSourceLevels(
                {
                    "dmg-step-wave-arp",
                    "DMG Wave",
                    "DMG Step Wave Arp",
                    "Stepped Wave RAM arp with light pulse reinforcement and split handheld routing.",
                    ChipMode::dmg,
                    AccuracyMode::hybrid,
                    MacroKind::arp,
                    PlayMode::stack,
                    { 0.42f, 0.28f, 0.14f, 0.74f },
                    { true, true, true, false },
                    0.18f,
                    4,
                    0,
                    0,
                    -10.0f,
                    4194304.0,
                    0.0f,
                    4
                },
                0.35f,
                0.22f,
                0.95f,
                1.0f),
            2),
        {
            "sid-filter-pluck",
            "SID PWM Leads",
            "SID Filter Pluck",
            "Pulse stack through the SID-style low-pass route for quick C64 plucks.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.42f, 0.22f, 0.25f, 0.35f },
            { true, true, true, false },
            0.62f,
            3,
            1,
            1,
            -10.0f,
            985248.0,
            0.68f,
            1,
            3,
            3,
            1
        },
        {
            "sid-8580-round-bass",
            "SID Bass",
            "SID 8580 Round Bass",
            "Cleaner 8580-style pulse bass with voices 1 and 2 routed into the filter.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::bass,
            PlayMode::stack,
            { 0.54f, 0.12f, 0.32f, 0.84f },
            { true, true, false, false },
            0.34f,
            3,
            1,
            1,
            -8.0f,
            985248.0,
            0.32f,
            2,
            3,
            0,
            5
        },
        {
            "sid-sync-saw-lead",
            "SID FX",
            "SID Sync Saw Lead",
            "Saw-led SID stack with sync-style control bits for sharper motion.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.36f, 0.58f, 0.62f, 0.64f },
            { true, true, true, false },
            0.22f,
            2,
            3,
            2,
            -11.0f,
            985248.0,
            0.45f,
            1,
            3,
            1,
            1
        },
        {
            "sid-ring-bell",
            "SID FX",
            "SID Ring Bell",
            "Triangle/pulse SID voice mix using ring-style control bits and band-pass filtering.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.50f, 0.46f, 0.48f, 0.58f },
            { true, true, true, false },
            0.46f,
            1,
            2,
            3,
            -12.0f,
            985248.0,
            0.60f,
            1,
            1,
            3,
            1
        },
        {
            "sid-noise-riser",
            "SID FX",
            "SID Noise Riser",
            "Filtered voice-3 noise with sync/ring grit for risers and impacts.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::laser,
            PlayMode::stack,
            { 0.50f, 0.84f, 0.76f, 0.30f },
            { false, true, true, false },
            0.88f,
            2,
            2,
            4,
            -12.0f,
            985248.0,
            0.85f,
            2,
            2,
            4,
            4
        },
        withSourceLevels(
            {
                "sid-filtered-noise-sweep",
                "SID FX",
                "SID Filtered Noise Sweep",
                "Noise-heavy SID sweep with saw support and voice-3 filter routing.",
                ChipMode::sid,
                AccuracyMode::hybrid,
                MacroKind::laser,
                PlayMode::stack,
                { 0.54f, 0.82f, 0.70f, 0.34f },
                { false, true, true, false },
                0.84f,
                4,
                2,
                2,
                -12.0f,
                985248.0,
                0.76f,
                1,
                2,
                4,
                4
            },
            0.20f,
            0.55f,
            0.82f,
            1.0f),
        {
            "sid-notch-pwm-keys",
            "SID PWM Leads",
            "SID Notch PWM Keys",
            "Pulse-stack keys using SID LP+HP notch bits with tight per-voice ADSR.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.62f, 0.33f, 0.55f, 0.64f },
            { true, true, true, false },
            0.42f,
            3,
            5,
            1,
            -10.0f,
            985248.0,
            0.52f,
            1,
            3,
            2,
            1,
            1,
            8,
            7,
            4,
            1,
            8,
            7,
            4,
            1,
            6,
            5,
            3,
            0.92f,
            0.78f,
            0.55f,
            1.0f
        },
        {
            "sid-lpbp-sweep-stack",
            "SID FX",
            "SID LP+BP Sweep Stack",
            "Saw/pulse stack through combined LP+BP filter bits for sweepable C64 leads.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::powerUp,
            PlayMode::stack,
            { 0.46f, 0.72f, 0.66f, 0.62f },
            { true, true, true, false },
            0.36f,
            2,
            6,
            2,
            -11.0f,
            985248.0,
            0.70f,
            2,
            3,
            1,
            1,
            2,
            9,
            10,
            5,
            2,
            8,
            9,
            5,
            1,
            7,
            8,
            4,
            0.88f,
            0.62f,
            0.45f,
            1.0f
        },
        {
            "sid-bphp-metal-bell",
            "SID FX",
            "SID BP+HP Metal Bell",
            "Ring-mod triangle/pulse stack through BP+HP filter bits with staggered ADSR.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.50f, 0.56f, 0.50f, 0.48f },
            { true, true, true, false },
            0.50f,
            1,
            7,
            3,
            -12.0f,
            985248.0,
            0.68f,
            1,
            3,
            1,
            1,
            1,
            6,
            3,
            8,
            1,
            7,
            4,
            9,
            1,
            8,
            5,
            10,
            0.65f,
            0.90f,
            0.52f,
            1.0f
        },
        {
            "sid-allmode-growl",
            "SID Bass",
            "SID All-Mode Growl",
            "Pulse, saw, and noise voices summed through all SID filter output bits.",
            ChipMode::sid,
            AccuracyMode::hybrid,
            MacroKind::bass,
            PlayMode::stack,
            { 0.40f, 0.30f, 0.42f, 0.88f },
            { true, true, true, false },
            0.30f,
            3,
            8,
            4,
            -12.0f,
            985248.0,
            0.80f,
            1,
            2,
            4,
            1,
            1,
            5,
            13,
            4,
            1,
            6,
            12,
            4,
            1,
            4,
            7,
            3,
            0.82f,
            0.58f,
            0.36f,
            1.0f
        },
        withSourceLevels(
            {
                "sid-pwm-bass-split",
                "SID Bass",
                "SID PWM Bass Split",
                "Two pulse voices through the SID low-pass route with a quiet saw edge and per-voice ADSR.",
                ChipMode::sid,
                AccuracyMode::hybrid,
                MacroKind::bass,
                PlayMode::stack,
                { 0.68f, 0.24f, 0.36f, 0.90f },
                { true, true, true, false },
                0.34f,
                3,
                1,
                1,
                -9.0f,
                985248.0,
                0.44f,
                2,
                3,
                2,
                5,
                1,
                5,
                14,
                4,
                1,
                6,
                12,
                4,
                1,
                8,
                7,
                5
            },
            0.90f,
            0.72f,
            0.28f,
            1.0f),
        withSourceLevels(
            {
                "sid-wide-pwm-pad",
                "SID PWM Leads",
                "SID Wide PWM Pad",
                "Three pulse voices with slow ADSR-style sustain and a warm 6581 low-pass route.",
                ChipMode::sid,
                AccuracyMode::hybrid,
                MacroKind::lead,
                PlayMode::stack,
                { 0.54f, 0.42f, 0.34f, 0.76f },
                { true, true, true, false },
                0.18f,
                3,
                1,
                1,
                -12.0f,
                985248.0,
                0.62f,
                1,
                3,
                3,
                1,
                3,
                9,
                12,
                8,
                4,
                10,
                11,
                8,
                5,
                11,
                10,
                9
            },
            0.72f,
            0.68f,
            0.60f,
            1.0f),
        withSourceLevels(
            {
                "sid-hard-sync-saw",
                "SID FX",
                "SID Hard Sync Saw",
                "Bright 8580 saw lead with sync bits enabled and voice 2 routed through the filter.",
                ChipMode::sid,
                AccuracyMode::hybrid,
                MacroKind::lead,
                PlayMode::stack,
                { 0.50f, 0.86f, 0.72f, 0.64f },
                { true, true, false, false },
                0.28f,
                2,
                3,
                2,
                -10.0f,
                985248.0,
                0.48f,
                2,
                2,
                2,
                3,
                1,
                6,
                9,
                4,
                1,
                7,
                8,
                5,
                1,
                7,
                8,
                5
            },
            0.86f,
            0.74f,
            0.0f,
            1.0f),
        withSourceLevels(
            {
                "sid-gated-noise-tom",
                "SID FX",
                "SID Gated Noise Tom",
                "Noise-led SID percussion with a pulse body, short release, and filtered voice 3 route.",
                ChipMode::sid,
                AccuracyMode::hybrid,
                MacroKind::drum,
                PlayMode::stack,
                { 0.42f, 0.14f, 0.58f, 0.24f },
                { true, false, true, false },
                0.86f,
                3,
                2,
                1,
                -11.0f,
                985248.0,
                0.70f,
                2,
                0,
                4,
                4,
                1,
                2,
                8,
                2,
                1,
                2,
                6,
                2,
                1,
                3,
                5,
                2
            },
            0.50f,
            0.0f,
            0.92f,
            1.0f),
        {
            "ym-bright-beep",
            "YM Beeps",
            "YM Bright Beep",
            "Single-channel AY/YM tone beep for menus and alerts.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::coin,
            PlayMode::stack,
            { 0.18f, 0.72f, 0.06f, 0.50f },
            { true, false, false, false },
            0.0f,
            0,
            0,
            0,
            -11.0f,
            2000000.0
        },
        {
            "ym-envelope-bell",
            "YM Beeps",
            "YM Envelope Bell",
            "Hardware-envelope-style triangle shape over three bright PSG tones.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.62f, 0.22f, 0.18f, 0.66f },
            { true, true, true, false },
            0.48f,
            0,
            4,
            0,
            -9.0f,
            2000000.0
        },
        {
            "ym-arcade-clang",
            "Classic Game SFX",
            "YM Arcade Clang",
            "Tone plus shared noise impact with a rising hardware envelope.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::hit,
            PlayMode::stack,
            { 0.42f, 0.34f, 0.76f, 0.96f },
            { true, true, false, true },
            0.55f,
            0,
            2,
            0,
            -12.0f,
            2000000.0
        },
        {
            "ym-fast-minor-arp",
            "YM Arps",
            "YM Fast Minor Arp",
            "Three-channel fake minor chord with tight demo-scene motion.",
            ChipMode::ym2149,
            AccuracyMode::hybrid,
            MacroKind::arp,
            PlayMode::chipPoly,
            { 0.82f, 0.86f, 0.10f, 0.54f },
            { true, true, true, false },
            0.0f,
            0,
            0,
            0,
            -10.0f,
            2000000.0
        },
        withSourceLevels(
            {
                "ym-triangle-env-keys",
                "YM Beeps",
                "YM Triangle Env Keys",
                "Three square channels under a repeating hardware-envelope triangle contour.",
                ChipMode::ym2149,
                AccuracyMode::hybrid,
                MacroKind::lead,
                PlayMode::stack,
                { 0.58f, 0.26f, 0.22f, 0.62f },
                { true, true, true, false },
                0.82f,
                0,
                4,
                0,
                -10.0f,
                2000000.0
            },
            0.95f,
            0.68f,
            0.48f,
            1.0f),
        {
            "sn-tone-stack",
            "SN76489 / Sega PSG",
            "PSG Tone Stack",
            "Three SN76489 tone lanes stacked for bright Sega-style leads.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::lead,
            PlayMode::stack,
            { 0.78f, 0.34f, 0.08f, 0.12f },
            { true, true, true, false },
            0.0f,
            0,
            0,
            0,
            -7.0f,
            3579545.0
        },
        {
            "sn-arcade-bass",
            "SN76489 / Sega PSG",
            "PSG Arcade Bass",
            "Low square-wave bass centered on the first PSG tone channel.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::bass,
            PlayMode::stack,
            { 0.36f, 0.12f, 0.04f, 0.08f },
            { true, false, false, false },
            0.0f,
            0,
            0,
            0,
            -8.0f,
            3579545.0
        },
        {
            "sn-periodic-zap",
            "Classic Game SFX",
            "PSG Periodic Zap",
            "SN76489 periodic-noise zap paired with a tone sweep.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::laser,
            PlayMode::stack,
            { 0.28f, 0.88f, 0.52f, 0.78f },
            { true, false, false, true },
            0.0f,
            0,
            0,
            2,
            -11.0f,
            3579545.0
        },
        {
            "sn-warning-alarm",
            "Arcade UI",
            "PSG Warning Alarm",
            "Two-tone PSG warning chirp with a white-noise edge.",
            ChipMode::sn76489,
            AccuracyMode::hybrid,
            MacroKind::jump,
            PlayMode::stack,
            { 0.64f, 0.70f, 0.82f, 0.42f },
            { true, true, false, true },
            0.0f,
            0,
            0,
            4,
            -11.0f,
            3579545.0
        },
        withSourceLevels(
            {
                "sn-periodic-bass-click",
                "SN76489 / Sega PSG",
                "PSG Periodic Bass Click",
                "Tone-1 bass with a periodic-noise click for Sega-style low-end accents.",
                ChipMode::sn76489,
                AccuracyMode::hybrid,
                MacroKind::bass,
                PlayMode::stack,
                { 0.30f, 0.12f, 0.46f, 0.74f },
                { true, false, false, true },
                0.0f,
                0,
                0,
                2,
                -10.0f,
                3579545.0
            },
            0.92f,
            1.0f,
            1.0f,
            0.38f)
    };

    return presets;
}

std::vector<const PresetInfo*> presetsForChip(ChipMode chip)
{
    std::vector<const PresetInfo*> matches;
    for (const auto& preset : presetCatalog())
    {
        if (preset.chip == chip)
            matches.push_back(&preset);
    }

    return matches;
}

const PresetInfo* presetById(std::string_view idOrName)
{
    const auto key = presetKey(idOrName);
    const auto& presets = presetCatalog();
    const auto iter = std::find_if(presets.begin(), presets.end(), [&key](const auto& preset)
    {
        return presetKey(preset.id) == key || presetKey(preset.name) == key;
    });

    return iter != presets.end() ? &*iter : nullptr;
}

PatchConfig patchConfigForPreset(const PresetInfo& preset)
{
    return makePatchConfig(preset.chip,
                           preset.macro,
                           preset.controls[0],
                           preset.controls[1],
                           preset.controls[2],
                           preset.controls[3],
                           preset.playMode,
                           preset.sourceEnabled,
                           { preset.source1Level, preset.source2Level, preset.source3Level, preset.source4Level },
                           preset.stereoSpread,
                           preset.envelopeDecay,
                           preset.waveShape,
                           0,
                           preset.dmgWaveLevel,
                           preset.dmgStereoRoute,
                           preset.ymEnvelopeShape,
                           0,
                           0,
                           0,
                           preset.snNoiseMode,
                           preset.sidVoice2WaveShape,
                           preset.sidVoice3WaveShape,
                           preset.sidAttack,
                           preset.sidDecay,
                           preset.sidSustain,
                           preset.sidRelease,
                           preset.sidVoice2Attack,
                           preset.sidVoice2Decay,
                           preset.sidVoice2Sustain,
                           preset.sidVoice2Release,
                           preset.sidVoice3Attack,
                           preset.sidVoice3Decay,
                           preset.sidVoice3Sustain,
                           preset.sidVoice3Release,
                           preset.sidFilterRouting,
                           preset.controls[0],
                           preset.controls[0],
                           preset.nesDmcDirectLevel);
}

} // namespace chipper
